RecipesBundle\Entity\Recipe:
    properties:
        name:
            - NotBlank: ~
            - Length:
                max: 5
                maxMessage: 'Your first name cannot be longer than {{ limit }} characters'