<?php

namespace RecipesBundle\Repository;

/**
 * RecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Returns all categories ordered by title ascendant.
     *
     * @return \RecipesBundle\Entity\Recipe
     */
    public function getRecipes()
    {
        return $this->findBy([], [ 'name' => 'ASC' ]);
    }
}
