FOS\UserBundle\Model\User:
    exclusion_policy: ALL
    properties:
        username:
            expose: true
            type: string
        lastLogin:
            expose: true
        email:
            expose: true
            type: string
        groups:
            expose: true